version: "3.8"

networks:
  proxy:
    external: true
  backend:

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      PGHOST: db
      PGUSER: myuser
      PGPASSWORD: mypass
      PGDATABASE: mydb
      PGPORT: 5432
    networks:
      - proxy
      - backend
    depends_on:
      - db

volumes:
  pgdata:
