x-db-env: &db-env
  PGHOST: db
  PGUSER: myuser
  PGPASSWORD: mypass
  PGDATABASE: mydb
  PGPORT: 5432

networks:
  proxy:
    external: true
  backend:

volumes:
  db-data:

services:
  web:
    build: backend/.
    environment:
      <<: *db-env
    networks:
      - proxy
      - backend
    depends_on:
      - migrate

  migrate:
    build: database
    command: npm run migrate up
    networks:
      - backend
    environment:
      <<: *db-env
      DATABASE_URL: "postgres://${PGUSER}:${PGPASSWORD}@db:${PGPORT}/${PGDATABASE}"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - proxy
    depends_on:
      - web
